name: aapelix
version: '${project.version}'
main: aapelix.aapelix.Aapelix
api-version: 1.19
commands:
  fly:
    usage: /fly
    aliases: [f, togglefly, lento]
    permission: fly
  survival:
    description: Gamemode Survival
    usage: /gms
    aliases: [gms]
    permission: gms
  creative:
    description: Gamemode Creative
    usage: /gmc
    aliases: [ gmc ]
    permission: gmc
  spectator:
    description: Gamemode Spectator
    usage: /gmsp
    aliases: [ gmsp ]
    permission: gmsp
  adventure:
    description: Gamemode Adventure
    usage: /gma
    aliases: [ gma ]
    permission: gma
  duel:
    description: Duel someone
    usage: /duel <arg1> <arg2>
  title:
    usage: /title <arg1> <arg2> <arg3>
  pvp:
    usage: /pvp
    aliases: [ enablepvp ]
    permission: enablepvp
  msg:
    usage: /msg <arg1>
    aliases: [ message ]
  food:
    usage: /food
    aliases: [ infinitefood, ifood ]

